version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: "redis:alpine"
